version: 2

sources:
  - name: dev
    database: db
    tables:
      - name: raw_weather_data
        column:
          -name: id
          -name: city
          -name: temperature
          -name: weather_descriptions
          -name: wind_speed
          -name: time
          -name: inserted_at
          -name: utc_offset